import './globals.css'
import { Inter } from 'next/font/google'
import { Poppins } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

const PopinsLarge = Poppins({
  subsets: ['devanagari'],
  variable: '--font-popinsLarge',
  weight: '400',
})
const popins = Poppins({
  subsets: ['devanagari'],
  variable: '--font-popins',
  weight: '300',
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${inter.className} ${popins.className} ${PopinsLarge.variable}`}
      >
        {children}
      </body>
    </html>
  )
}
